### ISSUE TITLE
My story

### ISSUE THREAD

**Issue by Math-TECH-Hub** [ASKnet-Open-Training/CommunityRepairCafe#10] opened 2020-12-15 08:59 UTC
I can't see my story which I wrote before, what could be the problem?

**Comment by timmwille** [comment] 2020-12-15 13:04
@Math-TECH-Hub I think the Repair Cafe is not the Story place, are you talking about this Project here?:
https://github.com/ASKnet-Open-Training/ASKnet-Track-II-participants-stories-Community-Empowerment-2020-2021

**Comment by timmwille** [comment] 2020-12-18 22:34
where did you write it? in your repo? in this public/group repo?

**Comment by Math-TECH-Hub** [comment] 2020-12-19 07:37
Public repo where my story md is.
below is the pictures. Only seeing my photo files.
![Screenshot_20201219-100704](https://user-images.githubusercontent.com/57042950/102684020-27be5280-41e6-11eb-9d9b-a445890ebfb9.png)

**Comment by timmwille** [comment] 2020-12-22 09:55
@Math-TECH-Hub so let's move this issue over to the other Repo where the problem is?

**Comment by gibertgibs** [comment] 2021-01-06 20:28
I think the issue should be moved and we see a solution to it immediately we are running out of time.

**Comment by Math-TECH-Hub** [comment] 2021-01-07 04:15
how can I move it?

**Comment by timmwille** [comment] 2021-01-08 21:05
@Math-TECH-Hub either try to use the move function or if not possible due to missing rights you can just copy the topic and content and create a new issue in your repo to paste it there :)
after this you can just close this one here

**Closed as completed** 2021-01-12 00:17 UTC
